# Generated by Django 4.2.5 on 2023-10-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='votes2',
            field=models.IntegerField(default=0),
        ),
    ]
